### 뿌리기 API
POST http://localhost:8080/distribution
Accept: application/json
Content-Type: application/json
X-ROOM-ID: x283
X-USER-ID: 2993

{
  "amount": 1002,
  "people": 4
}


### 받기 API
PUT http://localhost:8080/distribution/ZnD
Accept: application/json
Content-Type: application/json
X-ROOM-ID: x283
X-USER-ID: 2341


### 조회 AP
GET http://localhost:8080/distribution/ZnD
Accept: application/json
Content-Type: application/json
X-ROOM-ID: x283
X-USER-ID: 2993